### ISSUE TITLE
$table change what does this do i cant see where is this function decleared

### ISSUE THREAD

**Issue by mohamedsharaf** [grimzy/laravel-mysql-spatial#18]
hi first thanks for amazing package i wish i reached here long time ago

as in readme

            $table->point('location')->change();

where is this function change() decleared ?

what you do to make point column not null so i can use index on it?

is there is a way to set default value for point ? point(0,0) is ok for me

**Comment by grimzy** [comment]
I'm not exactly sure where `change()` is defined but it is packaged with Laravel and requires `doctrine/dbal` to also be installed ([see the docs](https://laravel.com/docs/5.5/migrations#modifying-columns)).

> what you do to make point column not null so i can use index on it?

In your migrations, when defining your point column, just don't set it as `nullable` (the usual way).
When using `change()` in the documentation, it's to **ALTER** a table column that was previously set with `DEFAULT NULL`; you typically don't need to do this if you **CREATE** a table.

> is there is a way to set default value for point ? point(0,0) is ok for me

Unfortunately this is a MySQL limitation, similarly to BLOB/TEXT types, you can't set a default value to any `GEOMETRY` type, otherwise you get:
`SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column`.
Alternatively you can create a MySQL trigger that updates the value of your `POINT` column when inserting a `NULL` value in; something like:
```
delimiter //
create trigger my_point_trigger before insert on my_point_table
for each row
begin
   if (NEW.point_column is null ) then
      set NEW.point_column = ST_GeomFromText('POINT(0 0)');
   end if;
end
//
delimiter ;
```
_**(Untested)**_

**Comment by mohamedsharaf** [comment]
thx i ended in setting value in elequent boot to point
