### ISSUE TITLE
Problems running in-memory sqlite migrations containing spatial features

### ISSUE THREAD

**Issue by artaex** [grimzy/laravel-mysql-spatial#2]
While writing PHPUnit tests, I ran into a couple of issues after running migrations.

First of all, something's wrong with the dependency injection. An instance of `Illuminate\Database\Schema\Blueprint` is always passed, even if `Grimzy\LaravelMysqlSpatial\Schema\Blueprint` is used instead. May not be related to this package, but I haven't yet found a solution.

Secondly, after bypassing the above issue by using `$table->addColumn('point', 'column-name');` instead of `$table->point('column-name')`, the following exception is thrown using an in-memory sqlite database for testing:

> Error: Call to undefined method Illuminate\Database\Schema\Grammars\SQLiteGrammar::typePoint()

Any suggestions on how this could be fixed? If I'm doing something wrong, please let me know. It would be nice to document how to properly configure this package for testing.

**Comment by grimzy** [comment]
@artaex, this package is intended to be used with MySQL and therefore will not work with Sqlite. If you look [here](https://github.com/grimzy/laravel-mysql-spatial/blob/1.0.0/src/Connectors/ConnectionFactory.php#L25), you can see that the Grammar is only loaded when the database driver is set to `mysql`.

I can only advise you to run your tests on a MySQL database because Sqlite doesn't have the same features, behavior, nor syntax.

If for you the time it takes for running the tests is an issue, you can look at into running MySQL in memory; but that has other implications.

**Comment by MatanYadaev** [comment]
@grimzy Laravel doesn't support SQLite spatial columns and indexes, do you think there's a reason?

SQLite has an extension called SpatialLite, I guess you know it. Is this extension is not good enough to be implemented in the Laravel framework?
Or maybe Larave doesn't support this extension because no one asked for it, or no one sent a PR with this extension support? WDYT?

If Laravel was supporting this extension, do you think `laravel-mysql-spatial` package could also support SQLite? (with some adjustments)
Is that something you could accept?

I might be interested to take this as a project, as long it's feasible. I'll be glad to hear your opinion about it.
