### ISSUE TITLE
Does this work on mariadb?

### ISSUE THREAD

**Issue by jericopulvera** [grimzy/laravel-mysql-spatial#40]
Does this work on mariadb?

**Comment by grimzy** [comment]
Good question!
It should work with MariaDB as it shares the same API than MySQL and Laravel handles them with the same implementation.

**Comment by grimzy** [comment]
I've just run the integration tests contained in this package against a MariaDB 10.3 database and they all passed with the exception of tests including [st_distance_sphere](https://dev.mysql.com/doc/refman/5.7/en/spatial-convenience-functions.html#function_st-distance-sphere), which, turns out, is [not supported by MariaDB](https://mariadb.com/kb/en/library/mysqlmariadb-spatial-support-matrix/).

Note that `st_distance` and `st_distance_sphere` are the only spatial functions with integration tests so I haven't tested the others but I'm fairly confident that most of them will work.
