### ISSUE TITLE
why PointCollection minimum of two items?

### ISSUE THREAD

**Issue by patrick-radius** [grimzy/laravel-mysql-spatial#95]
I was wondering why the PointCollection constructor has a restriction on a minimum of 2 items.
As far as i know this is not a MySQL restriction, and i have a need for some records with only one (or zero) items in the multipoint column.

I am currently unable to do that.
Also i tried extending the MultiPoint class and override the constructor. But since the library is using a factory it wont use the extended class.

**Comment by grimzy** [comment]
Hi @patrick-radius, sorry for responding this late.

You're right, that's a bug; the `PointCollection` should not have this restriction and instead should restrict on a minimum of **one** item. Only the `Linestring` should have the restriction on two items.

I'm not allowing zero items in the geometry collections because we cannot save empty collections in MySQL; try this:
```
SET @multipt = ST_GeomFromText('MULTIPOINT()');

-- or

SET @line1 = ST_GeomFromText('LINESTRING(0 0)'); -- must be 2 items or more
SET @line2 = ST_GeomFromText('LINESTRING()');
```

----

Gonna work on a PR.

Thanks
